### ISSUE TITLE
getSelfStake call failed

### ISSUE THREAD

**Issue by aion-chris** [aionnetwork/protocol_contracts#4]
params
delegator: 0xa0b4b4e62e6a4f96b13fed66cf5b7c4053a0ca65795ba65486e252727bcc679c
pool:         0xa0b4b4e62e6a4f96b13fed66cf5b7c4053a0ca65795ba65486e252727bcc679c

rpc output: 
'0x'

aion v0.4.2.0a1be13ab 
====================
no log with vm=TRACE or DEBUG

aionr v0.2.6-1.9e68439
==========================
JNI V2                                                                                                                                                                                             [23/1938]
TransactionData [hash=0c1f5118c0760d0d995eb61ec16caea5fa0679d2fe8d9d9420c70b0994097dc6, nonce=0, destinationAddress=a01b68fa4f947ea4829bebdac148d1f7f8a0be9a8fd5ce33e1696932bef05356, value=0, data=21000c67
657453656c665374616b6522a0b4b4e62e6a4f96b13fed66cf5b7c4053a0ca65795ba65486e252727bcc679c, energyLimit=2251799813685248, energyPrice=1]
AVM Executor Thread 1 start  0
Block Difficulty: 20
JNI: try to get miner address
current Nonce = JNI: try getNonce of: 0000000000000000000000000000000000000000000000000000000000000000
2019-10-18 10:44:04  DEBUG vm line:374  get nonce of 0000000000000000000000000000000000000000000000000000000000000000
2019-10-18 10:44:04  DEBUG vm line:952  search local cache
2019-10-18 10:44:04  DEBUG vm line:312  avm_get_nonce: 0x0000000000000000000000000000000000000000000000000000000000000000 = 0
0
JNI: getBalance of 0000000000000000000000000000000000000000000000000000000000000000
2019-10-18 10:44:04  DEBUG vm line:365  get balance of: 0000000000000000000000000000000000000000000000000000000000000000
2019-10-18 10:44:04  DEBUG vm line:952  search local cache
2019-10-18 10:44:04  DEBUG vm line:261  avm_get_balance: 0x0000000000000000000000000000000000000000000000000000000000000000 = avm_value { bytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0] }
JNI: getBalance of 0000000000000000000000000000000000000000000000000000000000000000
JNI: getBalance of a01b68fa4f947ea4829bebdac148d1f7f8a0be9a8fd5ce33e1696932bef05356
2019-10-18 10:44:04  DEBUG vm line:365  get balance of: a01b68fa4f947ea4829bebdac148d1f7f8a0be9a8fd5ce33e1696932bef05356
2019-10-18 10:44:04  DEBUG vm line:952  search local cache
2019-10-18 10:44:04  DEBUG vm line:261  avm_get_balance: 0xa01b68fa4f947ea4829bebdac148d1f7f8a0be9a8fd5ce33e1696932bef05356 = avm_value { bytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 2, 192, 244, 90, 11, 153, 60, 19, 216] }
JNI: try getNonce of: 0000000000000000000000000000000000000000000000000000000000000000
2019-10-18 10:44:04  DEBUG vm line:425  avm_get_transformed_code: 0xa01b68fa4f947ea4829bebdac148d1f7f8a0be9a8fd5ce33e1696932bef05356
2019-10-18 10:44:04  DEBUG vm line:828  AVMExt get transformed code at: a01b68fa4f947ea4829bebdac148d1f7f8a0be9a8fd5ce33e1696932bef05356
2019-10-18 10:44:04  DEBUG vm line:952  search local cache
2019-10-18 10:44:04  DEBUG vm line:537  get transformed code of: a01b68fa4f947ea4829bebdac148d1f7f8a0be9a8fd5ce33e1696932bef05356
JNI: try updating object graph
2019-10-18 10:44:04  DEBUG vm line:465  avm_get_objectgraph: 0xa01b68fa4f947ea4829bebdac148d1f7f8a0be9a8fd5ce33e1696932bef05356
2019-10-18 10:44:04  DEBUG vm line:848  AVMExt get object graph
2019-10-18 10:44:04  DEBUG vm line:952  search local cache
2019-10-18 10:44:04  DEBUG vm line:505  get object graph of: a01b68fa4f947ea4829bebdac148d1f7f8a0be9a8fd5ce33e1696932bef05356
DApp execution to REVERT due to uncaught EXCEPTION: "null"
i.RevertException
        at org.aion.avm.core.BlockchainRuntimeImpl.avm_revert(BlockchainRuntimeImpl.java:475)
        at p.avm.Blockchain.avm_revert(Blockchain.java:228)
        at u.A.avm_w(Unknown Source)
        at u.A.avm_main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.aion.avm.core.persistence.LoadedDApp.callMain(LoadedDApp.java:246)
        at org.aion.avm.core.DAppExecutor.call(DAppExecutor.java:117)
        at org.aion.avm.core.AvmImpl.commonInvoke(AvmImpl.java:551)
        at org.aion.avm.core.AvmImpl.runExternalInvoke(AvmImpl.java:395)
        at org.aion.avm.core.AvmImpl.backgroundProcessTransaction(AvmImpl.java:271)
        at org.aion.avm.core.AvmImpl.access$300(AvmImpl.java:29)
        at org.aion.avm.core.AvmImpl$AvmExecutorThread.run(AvmImpl.java:104)
JNI: getBalance of a0f682a5a9bd4442e5f896e605a24fbfcbbb05348fb3e31a05e27f61e31bdd94
2019-10-18 10:44:04  DEBUG vm line:365  get balance of: a0f682a5a9bd4442e5f896e605a24fbfcbbb05348fb3e31a05e27f61e31bdd94

**Comment by aion-chris** [comment]
Invalid use for private method call. Close ticket.

**Comment by aion-shidokht** [comment]
`getSelfStake` is a private method and it's only used internally by the contract. In order to retrieve the stake, `getStake` method should be used.
